export const NIFTY_100_SYMBOLS = [
  'RELIANCE.NS', 'HDFCBANK.NS', 'BHARTIARTL.NS', 'ICICIBANK.NS', 'SBIN.NS',
  'TCS.NS', 'BAJFINANCE.NS', 'LT.NS', 'HINDUNILVR.NS', 'SUNPHARMA.NS',
  'MARUTI.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'INFY.NS', 'ADANIENT.NS',
  'AXISBANK.NS', 'TITAN.NS', 'KOTAKBANK.NS', 'M&M.NS', 'ITC.NS',
  'NTPC.NS', 'ULTRACEMCO.NS', 'HCLTECH.NS', 'BEL.NS', 'BAJAJFINSV.NS',
  'JSWSTEEL.NS', 'ONGC.NS', 'HAL.NS', 'BAJAJ-AUTO.NS', 'ETERNAL.NS',
  'COALINDIA.NS', 'POWERGRID.NS', 'ASIANPAINT.NS', 'DMART.NS', 'ADANIGREEN.NS',
  'SHRIRAMFIN.NS', 'TATASTEEL.NS', 'HINDZINC.NS', 'GRASIM.NS', 'HINDALCO.NS',
  'INDIGO.NS', 'EICHERMOT.NS', 'IOC.NS', 'ADANIENSOL.NS', 'DIVISLAB.NS',
  'SBILIFE.NS', 'TRENT.NS', 'WIPRO.NS', 'VBL.NS', 'TVSMOTOR.NS',
  'SOLARINDS.NS', 'DLF.NS', 'PIDILITIND.NS', 'HYUNDAI.NS', 'TORNTPHARM.NS',
  'JIOFIN.NS', 'MOTHERSON.NS', 'CHOLAFIN.NS', 'CUMMINSIND.NS', 'TATACAP.NS',
  'ABB.NS', 'CGPOWER.NS', 'PFC.NS', 'TECHM.NS', 'BPCL.NS',
  'BANKBARODA.NS', 'BRITANNIA.NS', 'APOLLOHOSP.NS', 'TMPV.NS', 'SIEMENS.NS',
  'UNIONBANK.NS', 'BOSCHLTD.NS', 'HDFCLIFE.NS', 'BAJAJHLDNG.NS', 'MUTHOOTFIN.NS',
  'PNB.NS', 'HDFCAMC.NS', 'TATAPOWER.NS', 'IRFC.NS', 'CIPLA.NS',
  'CANBK.NS', 'DRREDDY.NS', 'GAIL.NS', 'ZYDUSLIFE.NS', 'MAXHEALTH.NS',
  'LTM.NS', 'TATACONSUM.NS', 'AMBUJACEM.NS', 'GODREJCP.NS', 'VEDL.NS',
  'JINDALSTEL.NS', 'LODHA.NS', 'INDHOTEL.NS', 'MAZDOCK.NS', 'UNITDSPR.NS',
  'SHREECEM.NS', 'RECLTD.NS',
];

export const NIFTY_100_NAMES: Record<string, string> = {
  'RELIANCE.NS': 'Reliance Industries',
  'HDFCBANK.NS': 'HDFC Bank',
  'BHARTIARTL.NS': 'Bharti Airtel',
  'ICICIBANK.NS': 'ICICI Bank',
  'SBIN.NS': 'State Bank of India',
  'TCS.NS': 'Tata Consultancy Services',
  'BAJFINANCE.NS': 'Bajaj Finance',
  'LT.NS': 'Larsen & Toubro',
  'HINDUNILVR.NS': 'Hindustan Unilever',
  'SUNPHARMA.NS': 'Sun Pharmaceutical',
  'MARUTI.NS': 'Maruti Suzuki',
  'ADANIPORTS.NS': 'Adani Ports & SEZ',
  'ADANIPOWER.NS': 'Adani Power',
  'INFY.NS': 'Infosys',
  'ADANIENT.NS': 'Adani Enterprises',
  'AXISBANK.NS': 'Axis Bank',
  'TITAN.NS': 'Titan Company',
  'KOTAKBANK.NS': 'Kotak Mahindra Bank',
  'M&M.NS': 'Mahindra & Mahindra',
  'ITC.NS': 'ITC',
  'NTPC.NS': 'NTPC',
  'ULTRACEMCO.NS': 'UltraTech Cement',
  'HCLTECH.NS': 'HCL Technologies',
  'BEL.NS': 'Bharat Electronics',
  'BAJAJFINSV.NS': 'Bajaj Finserv',
  'JSWSTEEL.NS': 'JSW Steel',
  'ONGC.NS': 'Oil & Natural Gas Corp',
  'HAL.NS': 'Hindustan Aeronautics',
  'BAJAJ-AUTO.NS': 'Bajaj Auto',
  'ETERNAL.NS': 'Eternal',
  'COALINDIA.NS': 'Coal India',
  'POWERGRID.NS': 'Power Grid Corp',
  'ASIANPAINT.NS': 'Asian Paints',
  'DMART.NS': 'Avenue Supermarts',
  'ADANIGREEN.NS': 'Adani Green Energy',
  'SHRIRAMFIN.NS': 'Shriram Finance',
  'TATASTEEL.NS': 'Tata Steel',
  'HINDZINC.NS': 'Hindustan Zinc',
  'GRASIM.NS': 'Grasim Industries',
  'HINDALCO.NS': 'Hindalco Industries',
  'INDIGO.NS': 'InterGlobe Aviation',
  'EICHERMOT.NS': 'Eicher Motors',
  'IOC.NS': 'Indian Oil Corp',
  'ADANIENSOL.NS': 'Adani Energy Solutions',
  'DIVISLAB.NS': 'Divi\'s Laboratories',
  'SBILIFE.NS': 'SBI Life Insurance',
  'TRENT.NS': 'Trent',
  'WIPRO.NS': 'Wipro',
  'VBL.NS': 'Varun Beverages',
  'TVSMOTOR.NS': 'TVS Motor',
  'SOLARINDS.NS': 'Solar Industries',
  'DLF.NS': 'DLF',
  'PIDILITIND.NS': 'Pidilite Industries',
  'HYUNDAI.NS': 'Hyundai Motor India',
  'TORNTPHARM.NS': 'Torrent Pharmaceuticals',
  'JIOFIN.NS': 'Jio Financial Services',
  'MOTHERSON.NS': 'Motherson Sumi',
  'CHOLAFIN.NS': 'Cholamandalam Investment',
  'CUMMINSIND.NS': 'Cummins India',
  'TATACAP.NS': 'Tata Capital',
  'ABB.NS': 'ABB India',
  'CGPOWER.NS': 'CG Power & Industrial',
  'PFC.NS': 'Power Finance Corp',
  'TECHM.NS': 'Tech Mahindra',
  'BPCL.NS': 'Bharat Petroleum',
  'BANKBARODA.NS': 'Bank of Baroda',
  'BRITANNIA.NS': 'Britannia Industries',
  'APOLLOHOSP.NS': 'Apollo Hospitals',
  'TMPV.NS': 'Tata Motors',
  'SIEMENS.NS': 'Siemens',
  'UNIONBANK.NS': 'Union Bank of India',
  'BOSCHLTD.NS': 'Bosch',
  'HDFCLIFE.NS': 'HDFC Life Insurance',
  'BAJAJHLDNG.NS': 'Bajaj Holdings',
  'MUTHOOTFIN.NS': 'Muthoot Finance',
  'PNB.NS': 'Punjab National Bank',
  'HDFCAMC.NS': 'HDFC Asset Management',
  'TATAPOWER.NS': 'Tata Power',
  'IRFC.NS': 'Indian Railway Finance Corp',
  'CIPLA.NS': 'Cipla',
  'CANBK.NS': 'Canara Bank',
  'DRREDDY.NS': 'Dr. Reddy\'s Laboratories',
  'GAIL.NS': 'GAIL',
  'ZYDUSLIFE.NS': 'Zydus Lifesciences',
  'MAXHEALTH.NS': 'Max Healthcare',
  'LTM.NS': 'LTIMindtree',
  'TATACONSUM.NS': 'Tata Consumer Products',
  'AMBUJACEM.NS': 'Ambuja Cements',
  'GODREJCP.NS': 'Godrej Consumer Products',
  'VEDL.NS': 'Vedanta',
  'JINDALSTEL.NS': 'Jindal Steel & Power',
  'LODHA.NS': 'Macrotech Developers',
  'INDHOTEL.NS': 'Indian Hotels',
  'MAZDOCK.NS': 'Mazagon Dock Shipbuilders',
  'UNITDSPR.NS': 'United Spirits',
  'SHREECEM.NS': 'Shree Cement',
  'RECLTD.NS': 'REC',
};

export function nseSymbol(yahooSymbol: string): string {
  return yahooSymbol.replace('.NS', '');
}
